Algoritmo "ComissaoVendedor"
// Disciplina   : Lógica de Programação e Algoritmos
// Professor   : MSc. Tiago Antonio da Silva 
// Descrição   : Cálcula a Comissão de cada Vendedor do Exercicio do SLide da Aula 3
// Autor(a)    : Lindolfo Farias Fontes Neto
// Data atual  : 07/03/2025
Var
// Seção de Declarações das variáveis 


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 


Fimalgoritmo