Algoritmo "BEM VINDO"
// Disciplina   : Lógica de Programação e Algoritmos
// Professor   : MSc. Tiago Antonio da Silva 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : LINDOLFO FARIAS FONTES NETO
// Data atual  : 11/04/2025
Var
 nome : caracter


Inicio
escreval("REINO DIGITAL")
escreval("Olá, Qual o seu nome?")
leia(nome)
escreval("Bem vindo, nobre ", nome, " do reino da lógica!")


Fimalgoritmo